import type { Scholarship, Mentor, ScholarshipApplication } from "./types"

export const mockScholarships: Scholarship[] = [
  {
    id: 1,
    title: "Women in STEM Scholarship",
    provider: "Global Tech Foundation",
    amount: "$10,000",
    deadline: "May 15, 2025",
    category: "STEM",
    description: "For young women pursuing degrees in Science, Technology, Engineering, or Mathematics fields.",
    eligibility: {
      educationLevels: ["Secondary School", "Undergraduate"],
      countries: ["All"],
    },
    keywords: ["STEM", "Technology", "Science", "Engineering", "Mathematics", "Women"],
  },
  {
    id: 2,
    title: "Future Leaders Grant",
    provider: "African Development Bank",
    amount: "$5,000",
    deadline: "June 30, 2025",
    category: "Business",
    description: "Supporting young women with leadership potential in business and entrepreneurship.",
    eligibility: {
      educationLevels: ["Undergraduate", "Graduate"],
      countries: ["Nigeria", "Ghana", "Kenya", "South Africa"],
    },
    keywords: ["Business", "Leadership", "Entrepreneurship", "Africa"],
    isPremium: true,
  },
  {
    id: 3,
    title: "Creative Arts Fellowship",
    provider: "International Arts Council",
    amount: "$3,500",
    deadline: "July 10, 2025",
    category: "Arts",
    description: "For talented young women pursuing education in visual arts, music, literature, or performing arts.",
    eligibility: {
      educationLevels: ["Secondary School", "Undergraduate", "Graduate"],
      countries: ["All"],
    },
    keywords: ["Arts", "Creative", "Visual Arts", "Music", "Literature", "Performing Arts"],
  },
  {
    id: 4,
    title: "Healthcare Heroes Scholarship",
    provider: "World Health Foundation",
    amount: "$7,500",
    deadline: "August 1, 2025",
    category: "Healthcare",
    description: "Supporting future female healthcare professionals in medicine, nursing, and public health.",
    eligibility: {
      educationLevels: ["Undergraduate", "Graduate"],
      countries: ["All"],
    },
    keywords: ["Healthcare", "Medicine", "Nursing", "Public Health"],
    isPremium: true,
  },
  {
    id: 5,
    title: "Digital Innovation Award",
    provider: "Microsoft",
    amount: "$12,000",
    deadline: "September 15, 2025",
    category: "STEM",
    description: "For young women with innovative ideas in computer science, AI, or digital technology.",
    eligibility: {
      educationLevels: ["Secondary School", "Undergraduate", "Graduate"],
      countries: ["All"],
    },
    keywords: ["Technology", "Computer Science", "AI", "Digital", "Innovation"],
  },
  {
    id: 6,
    title: "Environmental Leadership Grant",
    provider: "Green Future Initiative",
    amount: "$4,000",
    deadline: "October 5, 2025",
    category: "STEM",
    description: "Supporting female students pursuing studies in environmental science and sustainability.",
    eligibility: {
      educationLevels: ["Undergraduate", "Graduate"],
      countries: ["All"],
    },
    keywords: ["Environment", "Sustainability", "Science", "Leadership"],
  },
  {
    id: 7,
    title: "Young African Scholars Program",
    provider: "Pan-African Education Trust",
    amount: "$8,000",
    deadline: "November 20, 2025",
    category: "General",
    description: "Comprehensive scholarship for high-achieving African girls to pursue higher education.",
    eligibility: {
      educationLevels: ["Secondary School"],
      countries: ["Nigeria", "Ghana", "Kenya", "South Africa", "Ethiopia", "Tanzania"],
    },
    keywords: ["Africa", "Education", "Academic Excellence"],
    isPremium: true,
  },
  {
    id: 8,
    title: "Women in Finance Scholarship",
    provider: "Goldman Sachs",
    amount: "$15,000",
    deadline: "December 10, 2025",
    category: "Business",
    description: "Supporting young women pursuing careers in finance, economics, and business administration.",
    eligibility: {
      educationLevels: ["Undergraduate", "Graduate"],
      countries: ["All"],
    },
    keywords: ["Finance", "Economics", "Business", "Banking"],
    isPremium: true,
  },
  {
    id: 9,
    title: "Tech Girls Rising Scholarship",
    provider: "Google",
    amount: "$20,000",
    deadline: "January 15, 2026",
    category: "STEM",
    description: "For exceptional young women interested in computer science and software engineering.",
    eligibility: {
      educationLevels: ["Secondary School", "Undergraduate"],
      countries: ["All"],
    },
    keywords: ["Technology", "Computer Science", "Software Engineering", "Coding"],
  },
  {
    id: 10,
    title: "Global Leadership Academy",
    provider: "United Nations Women",
    amount: "$6,500",
    deadline: "February 28, 2026",
    category: "Leadership",
    description:
      "Scholarship and leadership program for young women committed to social change and community development.",
    eligibility: {
      educationLevels: ["Undergraduate", "Graduate"],
      countries: ["All"],
    },
    keywords: ["Leadership", "Social Change", "Community Development", "Global"],
    isPremium: true,
  },
]

export const mockMentors: Mentor[] = [
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    title: "Computer Science Professor",
    institution: "MIT",
    field: "STEM",
    image: "/placeholder.svg?height=100&width=100",
    availability: "Available for mentoring",
    isPremium: true,
  },
  {
    id: 2,
    name: "Amina Diallo",
    title: "Business Consultant",
    institution: "McKinsey & Co.",
    field: "Business",
    image: "/placeholder.svg?height=100&width=100",
    availability: "2 spots available",
  },
  {
    id: 3,
    name: "Dr. Maya Patel",
    title: "Medical Researcher",
    institution: "Johns Hopkins University",
    field: "Healthcare",
    image: "/placeholder.svg?height=100&width=100",
    availability: "Available next month",
    isPremium: true,
  },
  {
    id: 4,
    name: "Prof. Elena Rodriguez",
    title: "Literature Professor",
    institution: "Oxford University",
    field: "Arts",
    image: "/placeholder.svg?height=100&width=100",
    availability: "Currently full",
  },
  {
    id: 5,
    name: "Dr. Fatima Al-Farsi",
    title: "Aerospace Engineer",
    institution: "NASA",
    field: "STEM",
    image: "/placeholder.svg?height=100&width=100",
    availability: "1 spot available",
    isPremium: true,
  },
  {
    id: 6,
    name: "Grace Okonkwo",
    title: "Finance Director",
    institution: "Goldman Sachs",
    field: "Business",
    image: "/placeholder.svg?height=100&width=100",
    availability: "Available for mentoring",
    isPremium: true,
  },
]

export const mockApplications: ScholarshipApplication[] = []
